apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base/nginx
patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
configMapGenerator:
  - name: my-config
    files:
      - configs/index.html
secretGenerator:
  - name: secret-token
    files:
      - secrets/token